name: Update all Subscribers
on:
  schedule:
    # Run daily
    - cron:  '0 12 * * *'
  workflow_dispatch:
jobs:
  build-matrix:
    name: "Build update matrix"
    runs-on: ubuntu-latest
    outputs:
      include: ${{ steps.generate-matrix.outputs.include }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: generate-matrix
        run: |
          MATRIX="$(jq 'reduce inputs as $in ([.]; . + [$in])' subscribers/*.json -c)"
          echo "include=$MATRIX" >> "$GITHUB_OUTPUT"
  integrate-package:
    name: Integrate "${{ matrix.recipeName }}"
    runs-on: ubuntu-latest
    needs: build-matrix
    strategy:
      matrix:
        include: ${{ fromJson(needs.build-matrix.outputs.include) }}
    steps:
      - run: |
          echo "Integrating ${{ matrix.recipeName }} for ${{ matrix.sourceRepo }}"