name: Update all Subscribers
on:
  schedule:
    # Run daily
    - cron:  '0 12 * * *'
  workflow_dispatch:
jobs:
  build-matrix:
    name: "Build update matrix"
    runs-on: ubuntu-latest
    outputs:
      include: ${{ steps.generate-matrix.outputs.include }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: generate-matrix
        run: |
          # Use JQ to reformat sourceMaintainers as a comma delimited list
          MATRIX="$(jq -n 'reduce inputs as $in ([]; . + [$in | .sourceMaintainers = (.sourceMaintainers | join(","))])'  subscribers/*.json -c)"
          echo "include=$MATRIX" >> "$GITHUB_OUTPUT"
  integrate-package:
    name: Integrate "${{ matrix.recipeName }}"
    runs-on: ubuntu-latest
    needs: build-matrix
    strategy:
      matrix:
        include: ${{ fromJson(needs.build-matrix.outputs.include) }}
    steps:
#      - uses: actions/setup-python@v4
#        with:
#          python-version: '3.11'
#          cache: 'pip'
#      - run: python3 -m pip install pyyaml
      - run: >-
          python3 -m python integrate-pr
          --repo "${{ matrix.sourceRepo }}"
          --package "${{ matrix.packageName }}"
          --recipe "${{ matrix.recipeName }}"
          ${{ matrix.prAsReady && '--ready-for-review' || '--not-ready-for-review' }}
          --maintainers "${{ matrix.sourceMaintainers }}"
          --commit 'Update {recipe} to {version}'
          --title "${{ matrix.prTitlePattern || 'Upgrade {recipe} to {version}' }}"
          --body "${{ matrix.prBodyPattern || 'This PR was created by a bot. Pinging {maintainers} to check this' }}"
            
